services:
  backend:
    build: ./backend
    ports:
      - "5174:5174"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mypass123@db:5432/user_management_db
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  db:
    image: postgres:17.4
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_PASSWORD=mypass123
      - POSTGRES_DB=user-management-db
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - user-management-app_pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  user-management-app_pgdata:

networks:
  app-network:
    driver: bridge
